// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Card struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	NoteID       pgtype.UUID
	Front        string
	Back         string
	EaseFactor   pgtype.Float4
	IntervalDays pgtype.Int4
	NextReview   pgtype.Timestamptz
	Reviews      pgtype.Int4
	CreatedAt    pgtype.Timestamptz
}

type Note struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Title     string
	Content   pgtype.Text
	Subject   pgtype.Text
	Chapter   pgtype.Text
	Tags      []string
	Embedding pgvector.Vector
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Resource struct {
	ID           pgtype.UUID
	Title        string
	Url          pgtype.Text
	ResourceType pgtype.Text
	Subject      pgtype.Text
	Language     pgtype.Text
	Embedding    pgvector.Vector
	CreatedAt    pgtype.Timestamptz
}

type StudySession struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	Subject         pgtype.Text
	DurationMinutes pgtype.Int4
	NotesStudied    pgtype.Int4
	StartedAt       pgtype.Timestamptz
	EndedAt         pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	Name         pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
