// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCard = `-- name: CreateCard :one
INSERT INTO cards (user_id, note_id, front, back)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, note_id, front, back, ease_factor, interval_days, next_review, reviews, created_at
`

type CreateCardParams struct {
	UserID pgtype.UUID
	NoteID pgtype.UUID
	Front  string
	Back   string
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.UserID,
		arg.NoteID,
		arg.Front,
		arg.Back,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NoteID,
		&i.Front,
		&i.Back,
		&i.EaseFactor,
		&i.IntervalDays,
		&i.NextReview,
		&i.Reviews,
		&i.CreatedAt,
	)
	return i, err
}

const createNote = `-- name: CreateNote :one
INSERT INTO notes (user_id, title, content, subject, chapter, tags)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, title, content, subject, chapter, tags, embedding, created_at, updated_at
`

type CreateNoteParams struct {
	UserID  pgtype.UUID
	Title   string
	Content pgtype.Text
	Subject pgtype.Text
	Chapter pgtype.Text
	Tags    []string
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote,
		arg.UserID,
		arg.Title,
		arg.Content,
		arg.Subject,
		arg.Chapter,
		arg.Tags,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.Subject,
		&i.Chapter,
		&i.Tags,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStudySession = `-- name: CreateStudySession :one
INSERT INTO study_sessions (user_id, subject)
VALUES ($1, $2)
RETURNING id, user_id, subject, duration_minutes, notes_studied, started_at, ended_at
`

type CreateStudySessionParams struct {
	UserID  pgtype.UUID
	Subject pgtype.Text
}

func (q *Queries) CreateStudySession(ctx context.Context, arg CreateStudySessionParams) (StudySession, error) {
	row := q.db.QueryRow(ctx, createStudySession, arg.UserID, arg.Subject)
	var i StudySession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Subject,
		&i.DurationMinutes,
		&i.NotesStudied,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, name, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	Name         pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes WHERE id = $1 AND user_id = $2
`

type DeleteNoteParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) error {
	_, err := q.db.Exec(ctx, deleteNote, arg.ID, arg.UserID)
	return err
}

const endStudySession = `-- name: EndStudySession :one
UPDATE study_sessions
SET ended_at = NOW(),
    duration_minutes = EXTRACT(EPOCH FROM (NOW() - started_at))::INTEGER / 60,
    notes_studied = $2
WHERE id = $1
RETURNING id, user_id, subject, duration_minutes, notes_studied, started_at, ended_at
`

type EndStudySessionParams struct {
	ID           pgtype.UUID
	NotesStudied pgtype.Int4
}

func (q *Queries) EndStudySession(ctx context.Context, arg EndStudySessionParams) (StudySession, error) {
	row := q.db.QueryRow(ctx, endStudySession, arg.ID, arg.NotesStudied)
	var i StudySession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Subject,
		&i.DurationMinutes,
		&i.NotesStudied,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getCardsByUser = `-- name: GetCardsByUser :many
SELECT id, user_id, note_id, front, back, ease_factor, interval_days, next_review, reviews, created_at FROM cards 
WHERE user_id = $1 AND next_review <= NOW()
ORDER BY next_review ASC
LIMIT 20
`

func (q *Queries) GetCardsByUser(ctx context.Context, userID pgtype.UUID) ([]Card, error) {
	rows, err := q.db.Query(ctx, getCardsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NoteID,
			&i.Front,
			&i.Back,
			&i.EaseFactor,
			&i.IntervalDays,
			&i.NextReview,
			&i.Reviews,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotesByUser = `-- name: GetNotesByUser :many
SELECT id, user_id, title, content, subject, chapter, tags, embedding, created_at, updated_at FROM notes 
WHERE user_id = $1 
ORDER BY updated_at DESC
LIMIT $2 OFFSET $3
`

type GetNotesByUserParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetNotesByUser(ctx context.Context, arg GetNotesByUserParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, getNotesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.Subject,
			&i.Chapter,
			&i.Tags,
			&i.Embedding,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResourcesBySubject = `-- name: GetResourcesBySubject :many
SELECT id, title, url, resource_type, subject, language, embedding, created_at FROM resources 
WHERE subject = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetResourcesBySubjectParams struct {
	Subject pgtype.Text
	Limit   int32
}

func (q *Queries) GetResourcesBySubject(ctx context.Context, arg GetResourcesBySubjectParams) ([]Resource, error) {
	rows, err := q.db.Query(ctx, getResourcesBySubject, arg.Subject, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.ResourceType,
			&i.Subject,
			&i.Language,
			&i.Embedding,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCardReview = `-- name: UpdateCardReview :exec
UPDATE cards 
SET ease_factor = $2,
    interval_days = $3,
    next_review = NOW() + (interval '1 day' * $4),
    reviews = reviews + 1
WHERE id = $1
`

type UpdateCardReviewParams struct {
	ID           pgtype.UUID
	EaseFactor   pgtype.Float4
	IntervalDays pgtype.Int4
	Column4      interface{}
}

func (q *Queries) UpdateCardReview(ctx context.Context, arg UpdateCardReviewParams) error {
	_, err := q.db.Exec(ctx, updateCardReview,
		arg.ID,
		arg.EaseFactor,
		arg.IntervalDays,
		arg.Column4,
	)
	return err
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes 
SET title = $2, content = $3, subject = $4, chapter = $5, tags = $6, updated_at = NOW()
WHERE id = $1 AND user_id = $7
RETURNING id, user_id, title, content, subject, chapter, tags, embedding, created_at, updated_at
`

type UpdateNoteParams struct {
	ID      pgtype.UUID
	Title   string
	Content pgtype.Text
	Subject pgtype.Text
	Chapter pgtype.Text
	Tags    []string
	UserID  pgtype.UUID
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, updateNote,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Subject,
		arg.Chapter,
		arg.Tags,
		arg.UserID,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.Subject,
		&i.Chapter,
		&i.Tags,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
