// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package cache

import (
	"database/sql"
)

type NlmCache struct {
	ID           int64          `json:"id"`
	QueryHash    string         `json:"query_hash"`
	QueryText    string         `json:"query_text"`
	Subject      string         `json:"subject"`
	Topics       sql.NullString `json:"topics"`
	NotebookID   string         `json:"notebook_id"`
	S3Key        string         `json:"s3_key"`
	CreatedAt    sql.NullString `json:"created_at"`
	ExpiresAt    string         `json:"expires_at"`
	AccessCount  sql.NullInt64  `json:"access_count"`
	LastAccessed sql.NullString `json:"last_accessed"`
}
