// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package cache

import (
	"context"
	"database/sql"
)

const cleanupExpired = `-- name: CleanupExpired :exec
DELETE FROM nlm_cache WHERE expires_at < datetime('now')
`

func (q *Queries) CleanupExpired(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanupExpired)
	return err
}

const clearCache = `-- name: ClearCache :exec
DELETE FROM nlm_cache
`

func (q *Queries) ClearCache(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearCache)
	return err
}

const getCachedResponse = `-- name: GetCachedResponse :one
SELECT 
    id, query_hash, query_text, subject, topics, notebook_id, s3_key,
    created_at, expires_at, access_count, last_accessed
FROM nlm_cache 
WHERE query_hash = ?1 AND subject = ?2 AND expires_at > datetime('now')
`

type GetCachedResponseParams struct {
	QueryHash string `json:"query_hash"`
	Subject   string `json:"subject"`
}

func (q *Queries) GetCachedResponse(ctx context.Context, arg GetCachedResponseParams) (NlmCache, error) {
	row := q.db.QueryRowContext(ctx, getCachedResponse, arg.QueryHash, arg.Subject)
	var i NlmCache
	err := row.Scan(
		&i.ID,
		&i.QueryHash,
		&i.QueryText,
		&i.Subject,
		&i.Topics,
		&i.NotebookID,
		&i.S3Key,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AccessCount,
		&i.LastAccessed,
	)
	return i, err
}

const getStats = `-- name: GetStats :one
SELECT 
    COALESCE(SUM(access_count), 0) as hits,
    COUNT(*) as total
FROM nlm_cache
`

type GetStatsRow struct {
	Hits  interface{} `json:"hits"`
	Total int64       `json:"total"`
}

func (q *Queries) GetStats(ctx context.Context) (GetStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getStats)
	var i GetStatsRow
	err := row.Scan(&i.Hits, &i.Total)
	return i, err
}

const incrementAccessCount = `-- name: IncrementAccessCount :exec
UPDATE nlm_cache 
SET access_count = access_count + 1, last_accessed = datetime('now')
WHERE query_hash = ?1
`

func (q *Queries) IncrementAccessCount(ctx context.Context, queryHash string) error {
	_, err := q.db.ExecContext(ctx, incrementAccessCount, queryHash)
	return err
}

const setCacheEntry = `-- name: SetCacheEntry :exec
INSERT INTO nlm_cache 
    (query_hash, query_text, subject, topics, notebook_id, s3_key, expires_at, access_count, last_accessed)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, 1, datetime('now'))
ON CONFLICT(query_hash, subject) DO UPDATE SET
    access_count = access_count + 1,
    last_accessed = datetime('now')
`

type SetCacheEntryParams struct {
	QueryHash  string         `json:"query_hash"`
	QueryText  string         `json:"query_text"`
	Subject    string         `json:"subject"`
	Topics     sql.NullString `json:"topics"`
	NotebookID string         `json:"notebook_id"`
	S3Key      string         `json:"s3_key"`
	ExpiresAt  string         `json:"expires_at"`
}

func (q *Queries) SetCacheEntry(ctx context.Context, arg SetCacheEntryParams) error {
	_, err := q.db.ExecContext(ctx, setCacheEntry,
		arg.QueryHash,
		arg.QueryText,
		arg.Subject,
		arg.Topics,
		arg.NotebookID,
		arg.S3Key,
		arg.ExpiresAt,
	)
	return err
}
