// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type SubmissionSource string

const (
	SubmissionSourceImage      SubmissionSource = "image"
	SubmissionSourcePdf        SubmissionSource = "pdf"
	SubmissionSourceUrl        SubmissionSource = "url"
	SubmissionSourceManual     SubmissionSource = "manual"
	SubmissionSourceHistorical SubmissionSource = "historical"
	SubmissionSourceExam       SubmissionSource = "exam"
)

func (e *SubmissionSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubmissionSource(s)
	case string:
		*e = SubmissionSource(s)
	default:
		return fmt.Errorf("unsupported scan type for SubmissionSource: %T", src)
	}
	return nil
}

type NullSubmissionSource struct {
	SubmissionSource SubmissionSource `json:"submission_source"`
	Valid            bool             `json:"valid"` // Valid is true if SubmissionSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubmissionSource) Scan(value interface{}) error {
	if value == nil {
		ns.SubmissionSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubmissionSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubmissionSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubmissionSource), nil
}

type UserRole string

const (
	UserRoleStudent     UserRole = "student"
	UserRoleTeacher     UserRole = "teacher"
	UserRoleAdmin       UserRole = "admin"
	UserRoleSchoolAdmin UserRole = "school_admin"
	UserRoleModerator   UserRole = "moderator"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type VerificationStatus string

const (
	VerificationStatusPending  VerificationStatus = "pending"
	VerificationStatusApproved VerificationStatus = "approved"
	VerificationStatusRejected VerificationStatus = "rejected"
)

func (e *VerificationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VerificationStatus(s)
	case string:
		*e = VerificationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VerificationStatus: %T", src)
	}
	return nil
}

type NullVerificationStatus struct {
	VerificationStatus VerificationStatus `json:"verification_status"`
	Valid              bool               `json:"valid"` // Valid is true if VerificationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVerificationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VerificationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VerificationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVerificationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VerificationStatus), nil
}

type AnalyticsEvent struct {
	ID         pgtype.UUID      `json:"id"`
	EventType  string           `json:"event_type"`
	UserID     pgtype.UUID      `json:"user_id"`
	SubjectID  pgtype.Int4      `json:"subject_id"`
	QuestionID pgtype.UUID      `json:"question_id"`
	Properties []byte           `json:"properties"`
	SessionID  pgtype.UUID      `json:"session_id"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type Animation struct {
	ID               pgtype.UUID      `json:"id"`
	QuestionID       pgtype.UUID      `json:"question_id"`
	Title            pgtype.Text      `json:"title"`
	AnimationType    pgtype.Text      `json:"animation_type"`
	NoonCode         string           `json:"noon_code"`
	GenerationPrompt pgtype.Text      `json:"generation_prompt"`
	VideoPath        pgtype.Text      `json:"video_path"`
	ThumbnailPath    pgtype.Text      `json:"thumbnail_path"`
	DurationSeconds  pgtype.Int4      `json:"duration_seconds"`
	FileSizeMb       pgtype.Float8    `json:"file_size_mb"`
	GenerationStatus pgtype.Text      `json:"generation_status"`
	RenderedAt       pgtype.Timestamp `json:"rendered_at"`
	Views            pgtype.Int4      `json:"views"`
	Rating           pgtype.Float8    `json:"rating"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}

type AuditLog struct {
	ID              pgtype.UUID      `json:"id"`
	TransactionHash string           `json:"transaction_hash"`
	PreviousHash    string           `json:"previous_hash"`
	BlockNumber     pgtype.Int8      `json:"block_number"`
	Action          string           `json:"action"`
	TableName       string           `json:"table_name"`
	RecordID        pgtype.UUID      `json:"record_id"`
	Changes         []byte           `json:"changes"`
	Metadata        []byte           `json:"metadata"`
	UserID          pgtype.UUID      `json:"user_id"`
	IpAddress       *netip.Addr      `json:"ip_address"`
	UserAgent       pgtype.Text      `json:"user_agent"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type Badge struct {
	ID          int32       `json:"id"`
	Code        string      `json:"code"`
	NameFr      string      `json:"name_fr"`
	NameAr      string      `json:"name_ar"`
	Description pgtype.Text `json:"description"`
	Icon        pgtype.Text `json:"icon"`
	Criteria    []byte      `json:"criteria"`
	Rarity      pgtype.Text `json:"rarity"`
}

type Chapter struct {
	ID         int32       `json:"id"`
	SubjectID  pgtype.Int4 `json:"subject_id"`
	NameFr     string      `json:"name_fr"`
	NameAr     string      `json:"name_ar"`
	OrderIndex pgtype.Int4 `json:"order_index"`
	IsActive   pgtype.Bool `json:"is_active"`
}

type DailyStat struct {
	Date               pgtype.Date `json:"date"`
	ActiveUsers        int64       `json:"active_users"`
	TotalEvents        int64       `json:"total_events"`
	QuestionsAttempted int64       `json:"questions_attempted"`
	Submissions        int64       `json:"submissions"`
	CorrectAnswers     int64       `json:"correct_answers"`
}

type Leaderboard struct {
	ID          pgtype.UUID      `json:"id"`
	Period      string           `json:"period"`
	SubjectID   pgtype.Int4      `json:"subject_id"`
	Rankings    []byte           `json:"rankings"`
	GeneratedAt pgtype.Timestamp `json:"generated_at"`
}

type PointTransaction struct {
	ID          pgtype.UUID      `json:"id"`
	UserID      pgtype.UUID      `json:"user_id"`
	Points      int32            `json:"points"`
	Action      string           `json:"action"`
	ReferenceID pgtype.UUID      `json:"reference_id"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Prediction struct {
	ID                 pgtype.UUID      `json:"id"`
	SubjectID          pgtype.Int4      `json:"subject_id"`
	ChapterID          pgtype.Int4      `json:"chapter_id"`
	ExamYear           int32            `json:"exam_year"`
	ExamSession        pgtype.Text      `json:"exam_session"`
	PredictedTopics    []byte           `json:"predicted_topics"`
	PredictedQuestions []byte           `json:"predicted_questions"`
	ConfidenceScore    pgtype.Float8    `json:"confidence_score"`
	BasedOnPatterns    []byte           `json:"based_on_patterns"`
	HistoricalYears    []byte           `json:"historical_years"`
	MlModelVersion     pgtype.Text      `json:"ml_model_version"`
	Status             pgtype.Text      `json:"status"`
	PublishedAt        pgtype.Timestamp `json:"published_at"`
	AccuracyActual     []byte           `json:"accuracy_actual"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}

type Question struct {
	ID                 pgtype.UUID            `json:"id"`
	SubmittedBy        pgtype.UUID            `json:"submitted_by"`
	SourceType         SubmissionSource       `json:"source_type"`
	OriginalFilename   pgtype.Text            `json:"original_filename"`
	QuestionText       string                 `json:"question_text"`
	QuestionLatex      pgtype.Text            `json:"question_latex"`
	QuestionImage      []byte                 `json:"question_image"`
	SubjectID          pgtype.Int4            `json:"subject_id"`
	ChapterID          pgtype.Int4            `json:"chapter_id"`
	TopicTags          []string               `json:"topic_tags"`
	Difficulty         pgtype.Int4            `json:"difficulty"`
	QuestionType       pgtype.Text            `json:"question_type"`
	SolutionText       pgtype.Text            `json:"solution_text"`
	SolutionLatex      pgtype.Text            `json:"solution_latex"`
	SolutionSteps      []byte                 `json:"solution_steps"`
	CorrectAnswer      pgtype.Text            `json:"correct_answer"`
	AnswerOptions      []byte                 `json:"answer_options"`
	SourceExam         pgtype.Text            `json:"source_exam"`
	SourceYear         pgtype.Int4            `json:"source_year"`
	SourceSession      pgtype.Text            `json:"source_session"`
	SourceSchool       pgtype.Text            `json:"source_school"`
	VerifiedBy         pgtype.UUID            `json:"verified_by"`
	VerifiedAt         pgtype.Timestamp       `json:"verified_at"`
	VerificationStatus NullVerificationStatus `json:"verification_status"`
	RejectionReason    pgtype.Text            `json:"rejection_reason"`
	SubmissionCount    pgtype.Int4            `json:"submission_count"`
	CorrectCount       pgtype.Int4            `json:"correct_count"`
	ViewCount          pgtype.Int4            `json:"view_count"`
	SuccessRate        pgtype.Float8          `json:"success_rate"`
	AiDifficulty       pgtype.Float8          `json:"ai_difficulty"`
	AiConcepts         []byte                 `json:"ai_concepts"`
	AiAnalysis         []byte                 `json:"ai_analysis"`
	Embedding          pgvector.Vector        `json:"embedding"`
	ContentHash        string                 `json:"content_hash"`
	CreatedAt          pgtype.Timestamp       `json:"created_at"`
	UpdatedAt          pgtype.Timestamp       `json:"updated_at"`
}

type QuestionVersion struct {
	ID           pgtype.UUID      `json:"id"`
	QuestionID   pgtype.UUID      `json:"question_id"`
	Version      int32            `json:"version"`
	Diff         []byte           `json:"diff"`
	ChangedBy    pgtype.UUID      `json:"changed_by"`
	ChangeReason pgtype.Text      `json:"change_reason"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type QuestionsForPractice struct {
	ID           pgtype.UUID      `json:"id"`
	QuestionText string           `json:"question_text"`
	SolutionText pgtype.Text      `json:"solution_text"`
	Difficulty   pgtype.Int4      `json:"difficulty"`
	SuccessRate  pgtype.Float8    `json:"success_rate"`
	SubjectName  pgtype.Text      `json:"subject_name"`
	ChapterName  pgtype.Text      `json:"chapter_name"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type StorageObject struct {
	ID           pgtype.UUID      `json:"id"`
	Bucket       string           `json:"bucket"`
	ObjectKey    string           `json:"object_key"`
	Filename     pgtype.Text      `json:"filename"`
	ContentType  pgtype.Text      `json:"content_type"`
	FileSize     pgtype.Int8      `json:"file_size"`
	Checksum     pgtype.Text      `json:"checksum"`
	UploadedBy   pgtype.UUID      `json:"uploaded_by"`
	IsPublic     pgtype.Bool      `json:"is_public"`
	StorageClass pgtype.Text      `json:"storage_class"`
	ExpiresAt    pgtype.Timestamp `json:"expires_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type StudySession struct {
	ID                 pgtype.UUID      `json:"id"`
	UserID             pgtype.UUID      `json:"user_id"`
	SessionType        pgtype.Text      `json:"session_type"`
	SubjectID          pgtype.Int4      `json:"subject_id"`
	StartedAt          pgtype.Timestamp `json:"started_at"`
	EndedAt            pgtype.Timestamp `json:"ended_at"`
	DurationMinutes    pgtype.Int4      `json:"duration_minutes"`
	QuestionsAttempted pgtype.Int4      `json:"questions_attempted"`
	QuestionsCorrect   pgtype.Int4      `json:"questions_correct"`
	ScorePercentage    pgtype.Float8    `json:"score_percentage"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}

type Subject struct {
	ID         int32       `json:"id"`
	Code       string      `json:"code"`
	NameFr     string      `json:"name_fr"`
	NameAr     string      `json:"name_ar"`
	Icon       pgtype.Text `json:"icon"`
	Color      pgtype.Text `json:"color"`
	IsActive   pgtype.Bool `json:"is_active"`
	OrderIndex pgtype.Int4 `json:"order_index"`
}

type TopContributor struct {
	ID                 pgtype.UUID `json:"id"`
	Username           string      `json:"username"`
	FullName           pgtype.Text `json:"full_name"`
	School             pgtype.Text `json:"school"`
	Points             pgtype.Int4 `json:"points"`
	Level              pgtype.Int4 `json:"level"`
	StreakDays         pgtype.Int4 `json:"streak_days"`
	QuestionsSubmitted int64       `json:"questions_submitted"`
}

type User struct {
	ID                pgtype.UUID      `json:"id"`
	Username          string           `json:"username"`
	Email             pgtype.Text      `json:"email"`
	PasswordHash      string           `json:"password_hash"`
	FullName          pgtype.Text      `json:"full_name"`
	School            pgtype.Text      `json:"school"`
	Region            pgtype.Text      `json:"region"`
	Role              NullUserRole     `json:"role"`
	Points            pgtype.Int4      `json:"points"`
	Level             pgtype.Int4      `json:"level"`
	StreakDays        pgtype.Int4      `json:"streak_days"`
	TotalSolved       pgtype.Int4      `json:"total_solved"`
	AccuracyRate      pgtype.Float8    `json:"accuracy_rate"`
	PreferredLanguage pgtype.Text      `json:"preferred_language"`
	PreferredSubjects []string         `json:"preferred_subjects"`
	MfaEnabled        pgtype.Bool      `json:"mfa_enabled"`
	LastLogin         pgtype.Timestamp `json:"last_login"`
	IsActive          pgtype.Bool      `json:"is_active"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type UserBadge struct {
	ID       pgtype.UUID      `json:"id"`
	UserID   pgtype.UUID      `json:"user_id"`
	BadgeID  int32            `json:"badge_id"`
	EarnedAt pgtype.Timestamp `json:"earned_at"`
}

type UserProgress struct {
	ID               pgtype.UUID      `json:"id"`
	UserID           pgtype.UUID      `json:"user_id"`
	QuestionID       pgtype.UUID      `json:"question_id"`
	AttemptNumber    int32            `json:"attempt_number"`
	UserAnswer       pgtype.Text      `json:"user_answer"`
	IsCorrect        pgtype.Bool      `json:"is_correct"`
	TimeTakenSeconds pgtype.Int4      `json:"time_taken_seconds"`
	HintsUsed        pgtype.Int4      `json:"hints_used"`
	SolutionViewed   pgtype.Bool      `json:"solution_viewed"`
	AiFeedback       pgtype.Text      `json:"ai_feedback"`
	WeakConcepts     []string         `json:"weak_concepts"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}

type UserSession struct {
	ID         pgtype.UUID      `json:"id"`
	UserID     pgtype.UUID      `json:"user_id"`
	Token      string           `json:"token"`
	DeviceInfo []byte           `json:"device_info"`
	IpAddress  *netip.Addr      `json:"ip_address"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}
