// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const addChatMessage = `-- name: AddChatMessage :one
INSERT INTO ai_chat_messages (
    session_id, role, content, token_count, model, metadata
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, session_id, role, content, token_count, model, metadata, created_at
`

type AddChatMessageParams struct {
	SessionID  pgtype.UUID `json:"session_id"`
	Role       string      `json:"role"`
	Content    string      `json:"content"`
	TokenCount pgtype.Int4 `json:"token_count"`
	Model      pgtype.Text `json:"model"`
	Metadata   []byte      `json:"metadata"`
}

// Add a message to a chat session
func (q *Queries) AddChatMessage(ctx context.Context, arg AddChatMessageParams) (AiChatMessage, error) {
	row := q.db.QueryRow(ctx, addChatMessage,
		arg.SessionID,
		arg.Role,
		arg.Content,
		arg.TokenCount,
		arg.Model,
		arg.Metadata,
	)
	var i AiChatMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Content,
		&i.TokenCount,
		&i.Model,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const cleanupExpiredCache = `-- name: CleanupExpiredCache :exec
DELETE FROM api_cache WHERE expires_at IS NOT NULL AND expires_at < NOW()
`

// Delete expired cache entries
func (q *Queries) CleanupExpiredCache(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredCache)
	return err
}

const createChatSession = `-- name: CreateChatSession :one

INSERT INTO ai_chat_sessions (
    user_id, session_type, provider, model, title, context
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, session_type, provider, model, title, context, message_count, token_count, is_active, last_message_at, created_at, ended_at
`

type CreateChatSessionParams struct {
	UserID      pgtype.Int4 `json:"user_id"`
	SessionType string      `json:"session_type"`
	Provider    string      `json:"provider"`
	Model       pgtype.Text `json:"model"`
	Title       pgtype.Text `json:"title"`
	Context     []byte      `json:"context"`
}

// ============================================================================
// AI Chat Sessions Queries
// ============================================================================
// Create a new chat session
func (q *Queries) CreateChatSession(ctx context.Context, arg CreateChatSessionParams) (AiChatSession, error) {
	row := q.db.QueryRow(ctx, createChatSession,
		arg.UserID,
		arg.SessionType,
		arg.Provider,
		arg.Model,
		arg.Title,
		arg.Context,
	)
	var i AiChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionType,
		&i.Provider,
		&i.Model,
		&i.Title,
		&i.Context,
		&i.MessageCount,
		&i.TokenCount,
		&i.IsActive,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.EndedAt,
	)
	return i, err
}

const getAnalyticsEvents = `-- name: GetAnalyticsEvents :many
SELECT id, event_type, user_id, session_id, subject_id, question_id, properties, created_at
FROM analytics_events 
WHERE ($1::text IS NULL OR event_type = $1)
    AND ($2::int IS NULL OR user_id = $2)
    AND ($3::timestamp IS NULL OR created_at >= $3)
    AND ($4::timestamp IS NULL OR created_at <= $4)
ORDER BY created_at DESC 
LIMIT $5::int
`

type GetAnalyticsEventsParams struct {
	Column1 string           `json:"column_1"`
	Column2 int32            `json:"column_2"`
	Column3 pgtype.Timestamp `json:"column_3"`
	Column4 pgtype.Timestamp `json:"column_4"`
	Column5 int32            `json:"column_5"`
}

type GetAnalyticsEventsRow struct {
	ID         pgtype.UUID      `json:"id"`
	EventType  string           `json:"event_type"`
	UserID     pgtype.UUID      `json:"user_id"`
	SessionID  pgtype.UUID      `json:"session_id"`
	SubjectID  pgtype.Int4      `json:"subject_id"`
	QuestionID pgtype.UUID      `json:"question_id"`
	Properties []byte           `json:"properties"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

// Get analytics events with filters
func (q *Queries) GetAnalyticsEvents(ctx context.Context, arg GetAnalyticsEventsParams) ([]GetAnalyticsEventsRow, error) {
	rows, err := q.db.Query(ctx, getAnalyticsEvents,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAnalyticsEventsRow
	for rows.Next() {
		var i GetAnalyticsEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.UserID,
			&i.SessionID,
			&i.SubjectID,
			&i.QuestionID,
			&i.Properties,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCachedValue = `-- name: GetCachedValue :one

SELECT key, value, expires_at, created_at FROM api_cache WHERE key = $1 AND (expires_at IS NULL OR expires_at > NOW())
`

// ============================================================================
// Cache Queries
// ============================================================================
// Get a cached value by key
func (q *Queries) GetCachedValue(ctx context.Context, key string) (ApiCache, error) {
	row := q.db.QueryRow(ctx, getCachedValue, key)
	var i ApiCache
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getChatMessages = `-- name: GetChatMessages :many
SELECT id, session_id, role, content, token_count, model, metadata, created_at
FROM ai_chat_messages 
WHERE session_id = $1 
ORDER BY created_at ASC
`

// Get messages for a chat session
func (q *Queries) GetChatMessages(ctx context.Context, sessionID pgtype.UUID) ([]AiChatMessage, error) {
	rows, err := q.db.Query(ctx, getChatMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiChatMessage
	for rows.Next() {
		var i AiChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.TokenCount,
			&i.Model,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatSession = `-- name: GetChatSession :one
SELECT id, user_id, session_type, provider, model, title, context, message_count, token_count, is_active, last_message_at, created_at, ended_at 
FROM ai_chat_sessions WHERE id = $1
`

// Get a chat session by ID
func (q *Queries) GetChatSession(ctx context.Context, id pgtype.UUID) (AiChatSession, error) {
	row := q.db.QueryRow(ctx, getChatSession, id)
	var i AiChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionType,
		&i.Provider,
		&i.Model,
		&i.Title,
		&i.Context,
		&i.MessageCount,
		&i.TokenCount,
		&i.IsActive,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.EndedAt,
	)
	return i, err
}

const getSimilarQuestionsFilteredVec = `-- name: GetSimilarQuestionsFilteredVec :many
SELECT 
    q.question_text, 
    q.solution_text, 
    q.difficulty
FROM questions q
WHERE q.question_vector IS NOT NULL 
    AND ($2::int IS NULL OR q.difficulty = $2)
ORDER BY q.question_vector <=> $1::vector 
LIMIT 10
`

type GetSimilarQuestionsFilteredVecParams struct {
	Column1 pgvector.Vector `json:"column_1"`
	Column2 int32           `json:"column_2"`
}

type GetSimilarQuestionsFilteredVecRow struct {
	QuestionText string      `json:"question_text"`
	SolutionText pgtype.Text `json:"solution_text"`
	Difficulty   pgtype.Int4 `json:"difficulty"`
}

// Get similar questions with difficulty filter
func (q *Queries) GetSimilarQuestionsFilteredVec(ctx context.Context, arg GetSimilarQuestionsFilteredVecParams) ([]GetSimilarQuestionsFilteredVecRow, error) {
	rows, err := q.db.Query(ctx, getSimilarQuestionsFilteredVec, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSimilarQuestionsFilteredVecRow
	for rows.Next() {
		var i GetSimilarQuestionsFilteredVecRow
		if err := rows.Scan(&i.QuestionText, &i.SolutionText, &i.Difficulty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSimilarQuestionsVec = `-- name: GetSimilarQuestionsVec :many
SELECT 
    question_text, 
    solution_text, 
    difficulty
FROM questions 
WHERE question_vector IS NOT NULL 
ORDER BY question_vector <=> $1::vector 
LIMIT 10
`

type GetSimilarQuestionsVecRow struct {
	QuestionText string      `json:"question_text"`
	SolutionText pgtype.Text `json:"solution_text"`
	Difficulty   pgtype.Int4 `json:"difficulty"`
}

// Get similar questions based on vector embedding similarity
func (q *Queries) GetSimilarQuestionsVec(ctx context.Context, dollar_1 pgvector.Vector) ([]GetSimilarQuestionsVecRow, error) {
	rows, err := q.db.Query(ctx, getSimilarQuestionsVec, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSimilarQuestionsVecRow
	for rows.Next() {
		var i GetSimilarQuestionsVecRow
		if err := rows.Scan(&i.QuestionText, &i.SolutionText, &i.Difficulty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserActivitySummary = `-- name: GetUserActivitySummary :many
SELECT 
    activity_type,
    COUNT(*) as count,
    SUM(points_earned) as total_points
FROM user_activity_timeline 
WHERE user_id = $1 
    AND created_at >= $2 
    AND created_at <= $3
GROUP BY activity_type
`

type GetUserActivitySummaryParams struct {
	UserID      pgtype.Int4        `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type GetUserActivitySummaryRow struct {
	ActivityType string `json:"activity_type"`
	Count        int64  `json:"count"`
	TotalPoints  int64  `json:"total_points"`
}

// Get user activity summary for a time period
func (q *Queries) GetUserActivitySummary(ctx context.Context, arg GetUserActivitySummaryParams) ([]GetUserActivitySummaryRow, error) {
	rows, err := q.db.Query(ctx, getUserActivitySummary, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserActivitySummaryRow
	for rows.Next() {
		var i GetUserActivitySummaryRow
		if err := rows.Scan(&i.ActivityType, &i.Count, &i.TotalPoints); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertQuestion = `-- name: InsertQuestion :exec
INSERT INTO questions (
    question_text, 
    solution_text, 
    question_vector, 
    topic_tags, 
    difficulty
) VALUES (
    $1, $2, $3, $4, $5
)
`

type InsertQuestionParams struct {
	Column1 pgtype.Text     `json:"column_1"`
	Column2 pgtype.Text     `json:"column_2"`
	Column3 pgvector.Vector `json:"column_3"`
	Column4 []string        `json:"column_4"`
	Column5 pgtype.Int4     `json:"column_5"`
}

// Insert a new question with its solution and embedding
func (q *Queries) InsertQuestion(ctx context.Context, arg InsertQuestionParams) error {
	_, err := q.db.Exec(ctx, insertQuestion,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	return err
}

const insertRAGDocument = `-- name: InsertRAGDocument :one

INSERT INTO rag_documents (
    title, content, source_type, source_url, subject_id, chapter_id, embedding, metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, title, content, source_type, source_url, subject_id, chapter_id, embedding, metadata, chunk_count, indexed_at, created_at
`

type InsertRAGDocumentParams struct {
	Title      string          `json:"title"`
	Content    string          `json:"content"`
	SourceType pgtype.Text     `json:"source_type"`
	SourceUrl  pgtype.Text     `json:"source_url"`
	SubjectID  pgtype.Int4     `json:"subject_id"`
	ChapterID  pgtype.Int4     `json:"chapter_id"`
	Embedding  pgvector.Vector `json:"embedding"`
	Metadata   []byte          `json:"metadata"`
}

// ============================================================================
// RAG Document Queries
// ============================================================================
// Insert a RAG document
func (q *Queries) InsertRAGDocument(ctx context.Context, arg InsertRAGDocumentParams) (RagDocument, error) {
	row := q.db.QueryRow(ctx, insertRAGDocument,
		arg.Title,
		arg.Content,
		arg.SourceType,
		arg.SourceUrl,
		arg.SubjectID,
		arg.ChapterID,
		arg.Embedding,
		arg.Metadata,
	)
	var i RagDocument
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.SourceType,
		&i.SourceUrl,
		&i.SubjectID,
		&i.ChapterID,
		&i.Embedding,
		&i.Metadata,
		&i.ChunkCount,
		&i.IndexedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listChatSessions = `-- name: ListChatSessions :many
SELECT id, user_id, session_type, provider, model, title, context, message_count, token_count, is_active, last_message_at, created_at, ended_at
FROM ai_chat_sessions 
WHERE user_id = $1 AND is_active = true
ORDER BY last_message_at DESC 
LIMIT $2::int
`

type ListChatSessionsParams struct {
	UserID  pgtype.Int4 `json:"user_id"`
	Column2 int32       `json:"column_2"`
}

// List chat sessions for a user
func (q *Queries) ListChatSessions(ctx context.Context, arg ListChatSessionsParams) ([]AiChatSession, error) {
	rows, err := q.db.Query(ctx, listChatSessions, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiChatSession
	for rows.Next() {
		var i AiChatSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionType,
			&i.Provider,
			&i.Model,
			&i.Title,
			&i.Context,
			&i.MessageCount,
			&i.TokenCount,
			&i.IsActive,
			&i.LastMessageAt,
			&i.CreatedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAnalyticsEvent = `-- name: RecordAnalyticsEvent :one

INSERT INTO analytics_events (
    event_type, user_id, session_id, subject_id, question_id, properties
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, event_type, user_id, session_id, subject_id, question_id, properties, created_at
`

type RecordAnalyticsEventParams struct {
	EventType  string      `json:"event_type"`
	UserID     pgtype.Int4 `json:"user_id"`
	SessionID  pgtype.UUID `json:"session_id"`
	SubjectID  pgtype.Int4 `json:"subject_id"`
	QuestionID pgtype.Int4 `json:"question_id"`
	Properties []byte      `json:"properties"`
}

type RecordAnalyticsEventRow struct {
	ID         pgtype.UUID      `json:"id"`
	EventType  string           `json:"event_type"`
	UserID     pgtype.UUID      `json:"user_id"`
	SessionID  pgtype.UUID      `json:"session_id"`
	SubjectID  pgtype.Int4      `json:"subject_id"`
	QuestionID pgtype.UUID      `json:"question_id"`
	Properties []byte           `json:"properties"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

// ============================================================================
// Analytics Events Queries
// ============================================================================
// Record an analytics event
func (q *Queries) RecordAnalyticsEvent(ctx context.Context, arg RecordAnalyticsEventParams) (RecordAnalyticsEventRow, error) {
	row := q.db.QueryRow(ctx, recordAnalyticsEvent,
		arg.EventType,
		arg.UserID,
		arg.SessionID,
		arg.SubjectID,
		arg.QuestionID,
		arg.Properties,
	)
	var i RecordAnalyticsEventRow
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.UserID,
		&i.SessionID,
		&i.SubjectID,
		&i.QuestionID,
		&i.Properties,
		&i.CreatedAt,
	)
	return i, err
}

const searchQuestionsByText = `-- name: SearchQuestionsByText :many
SELECT 
    question_text, 
    solution_text, 
    difficulty
FROM questions 
WHERE question_text ILIKE $1 
LIMIT $2::int
`

type SearchQuestionsByTextParams struct {
	QuestionText string `json:"question_text"`
	Column2      int32  `json:"column_2"`
}

type SearchQuestionsByTextRow struct {
	QuestionText string      `json:"question_text"`
	SolutionText pgtype.Text `json:"solution_text"`
	Difficulty   pgtype.Int4 `json:"difficulty"`
}

// Search questions by text similarity
func (q *Queries) SearchQuestionsByText(ctx context.Context, arg SearchQuestionsByTextParams) ([]SearchQuestionsByTextRow, error) {
	rows, err := q.db.Query(ctx, searchQuestionsByText, arg.QuestionText, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchQuestionsByTextRow
	for rows.Next() {
		var i SearchQuestionsByTextRow
		if err := rows.Scan(&i.QuestionText, &i.SolutionText, &i.Difficulty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRAGDocumentsFilteredVec = `-- name: SearchRAGDocumentsFilteredVec :many
SELECT 
    id, title, content, source_type, source_url
FROM rag_documents 
WHERE embedding IS NOT NULL
    AND ($2::int IS NULL OR subject_id = $2)
    AND ($3::int IS NULL OR chapter_id = $3)
ORDER BY embedding <=> $1::vector 
LIMIT 10
`

type SearchRAGDocumentsFilteredVecParams struct {
	Column1 pgvector.Vector `json:"column_1"`
	Column2 int32           `json:"column_2"`
	Column3 int32           `json:"column_3"`
}

type SearchRAGDocumentsFilteredVecRow struct {
	ID         pgtype.UUID `json:"id"`
	Title      string      `json:"title"`
	Content    string      `json:"content"`
	SourceType pgtype.Text `json:"source_type"`
	SourceUrl  pgtype.Text `json:"source_url"`
}

// Search RAG documents with subject/chapter filters
func (q *Queries) SearchRAGDocumentsFilteredVec(ctx context.Context, arg SearchRAGDocumentsFilteredVecParams) ([]SearchRAGDocumentsFilteredVecRow, error) {
	rows, err := q.db.Query(ctx, searchRAGDocumentsFilteredVec, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchRAGDocumentsFilteredVecRow
	for rows.Next() {
		var i SearchRAGDocumentsFilteredVecRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.SourceType,
			&i.SourceUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRAGDocumentsVec = `-- name: SearchRAGDocumentsVec :many
SELECT 
    id, title, content, source_type, source_url
FROM rag_documents 
WHERE embedding IS NOT NULL
ORDER BY embedding <=> $1::vector 
LIMIT 10
`

type SearchRAGDocumentsVecRow struct {
	ID         pgtype.UUID `json:"id"`
	Title      string      `json:"title"`
	Content    string      `json:"content"`
	SourceType pgtype.Text `json:"source_type"`
	SourceUrl  pgtype.Text `json:"source_url"`
}

// Search RAG documents by vector similarity
func (q *Queries) SearchRAGDocumentsVec(ctx context.Context, dollar_1 pgvector.Vector) ([]SearchRAGDocumentsVecRow, error) {
	rows, err := q.db.Query(ctx, searchRAGDocumentsVec, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchRAGDocumentsVecRow
	for rows.Next() {
		var i SearchRAGDocumentsVecRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.SourceType,
			&i.SourceUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCacheValue = `-- name: SetCacheValue :exec
INSERT INTO api_cache (key, value, expires_at) 
VALUES ($1, $2, $3)
ON CONFLICT (key) DO UPDATE SET value = $2, expires_at = $3
`

type SetCacheValueParams struct {
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Set a cache value with optional expiry
func (q *Queries) SetCacheValue(ctx context.Context, arg SetCacheValueParams) error {
	_, err := q.db.Exec(ctx, setCacheValue, arg.Key, arg.Value, arg.ExpiresAt)
	return err
}
