// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// Get similar questions based on vector embedding similarity
	GetSimilarQuestions(ctx context.Context, arg GetSimilarQuestionsParams) ([]GetSimilarQuestionsRow, error)
	// Insert a new question with its solution and embedding
	InsertQuestion(ctx context.Context, arg InsertQuestionParams) error
	// Search questions by text similarity
	SearchQuestionsByText(ctx context.Context, arg SearchQuestionsByTextParams) ([]SearchQuestionsByTextRow, error)
}

var _ Querier = (*Queries)(nil)
