// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Querier interface {
	// Add a message to a chat session
	AddChatMessage(ctx context.Context, arg AddChatMessageParams) (AiChatMessage, error)
	// Delete expired cache entries
	CleanupExpiredCache(ctx context.Context) error
	// ============================================================================
	// AI Chat Sessions Queries
	// ============================================================================
	// Create a new chat session
	CreateChatSession(ctx context.Context, arg CreateChatSessionParams) (AiChatSession, error)
	// Get analytics events with filters
	GetAnalyticsEvents(ctx context.Context, arg GetAnalyticsEventsParams) ([]GetAnalyticsEventsRow, error)
	// ============================================================================
	// Cache Queries
	// ============================================================================
	// Get a cached value by key
	GetCachedValue(ctx context.Context, key string) (ApiCache, error)
	// Get messages for a chat session
	GetChatMessages(ctx context.Context, sessionID pgtype.UUID) ([]AiChatMessage, error)
	// Get a chat session by ID
	GetChatSession(ctx context.Context, id pgtype.UUID) (AiChatSession, error)
	// Get similar questions with difficulty filter
	GetSimilarQuestionsFilteredVec(ctx context.Context, arg GetSimilarQuestionsFilteredVecParams) ([]GetSimilarQuestionsFilteredVecRow, error)
	// Get similar questions based on vector embedding similarity
	GetSimilarQuestionsVec(ctx context.Context, dollar_1 pgvector.Vector) ([]GetSimilarQuestionsVecRow, error)
	// Get user activity summary for a time period
	GetUserActivitySummary(ctx context.Context, arg GetUserActivitySummaryParams) ([]GetUserActivitySummaryRow, error)
	// Insert a new question with its solution and embedding
	InsertQuestion(ctx context.Context, arg InsertQuestionParams) error
	// ============================================================================
	// RAG Document Queries
	// ============================================================================
	// Insert a RAG document
	InsertRAGDocument(ctx context.Context, arg InsertRAGDocumentParams) (RagDocument, error)
	// List chat sessions for a user
	ListChatSessions(ctx context.Context, arg ListChatSessionsParams) ([]AiChatSession, error)
	// ============================================================================
	// Analytics Events Queries
	// ============================================================================
	// Record an analytics event
	RecordAnalyticsEvent(ctx context.Context, arg RecordAnalyticsEventParams) (RecordAnalyticsEventRow, error)
	// Search questions by text similarity
	SearchQuestionsByText(ctx context.Context, arg SearchQuestionsByTextParams) ([]SearchQuestionsByTextRow, error)
	// Search RAG documents with subject/chapter filters
	SearchRAGDocumentsFilteredVec(ctx context.Context, arg SearchRAGDocumentsFilteredVecParams) ([]SearchRAGDocumentsFilteredVecRow, error)
	// Search RAG documents by vector similarity
	SearchRAGDocumentsVec(ctx context.Context, dollar_1 pgvector.Vector) ([]SearchRAGDocumentsVecRow, error)
	// Set a cache value with optional expiry
	SetCacheValue(ctx context.Context, arg SetCacheValueParams) error
}

var _ Querier = (*Queries)(nil)
