// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const getSimilarQuestions = `-- name: GetSimilarQuestions :many
SELECT 
    question_text, 
    solution_text, 
    difficulty,
    1 - (question_vector <=> $2::vector) as similarity
FROM questions 
WHERE question_vector IS NOT NULL 
ORDER BY question_vector <=> $2::vector 
LIMIT $1
`

type GetSimilarQuestionsParams struct {
	Limit   int64           `json:"limit"`
	Column2 pgvector.Vector `json:"column_2"`
}

type GetSimilarQuestionsRow struct {
	QuestionText string      `json:"question_text"`
	SolutionText pgtype.Text `json:"solution_text"`
	Difficulty   pgtype.Int4 `json:"difficulty"`
	Similarity   float64     `json:"similarity"`
}

// Get similar questions based on vector embedding similarity
func (q *Queries) GetSimilarQuestions(ctx context.Context, arg GetSimilarQuestionsParams) ([]GetSimilarQuestionsRow, error) {
	rows, err := q.db.Query(ctx, getSimilarQuestions, arg.Limit, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSimilarQuestionsRow
	for rows.Next() {
		var i GetSimilarQuestionsRow
		if err := rows.Scan(
			&i.QuestionText,
			&i.SolutionText,
			&i.Difficulty,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertQuestion = `-- name: InsertQuestion :exec
INSERT INTO questions (
    question_text, 
    solution_text, 
    question_vector, 
    topic_tags, 
    difficulty
) VALUES (
    $1, $2, $3, $4, $5
)
`

type InsertQuestionParams struct {
	Column1 pgtype.Text     `json:"column_1"`
	Column2 pgtype.Text     `json:"column_2"`
	Column3 pgvector.Vector `json:"column_3"`
	Column4 []string        `json:"column_4"`
	Column5 pgtype.Int4     `json:"column_5"`
}

// Insert a new question with its solution and embedding
func (q *Queries) InsertQuestion(ctx context.Context, arg InsertQuestionParams) error {
	_, err := q.db.Exec(ctx, insertQuestion,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	return err
}

const searchQuestionsByText = `-- name: SearchQuestionsByText :many
SELECT 
    question_text, 
    solution_text, 
    difficulty
FROM questions 
WHERE question_text ILIKE $1 
LIMIT $2
`

type SearchQuestionsByTextParams struct {
	QuestionText string `json:"question_text"`
	Limit        int64  `json:"limit"`
}

type SearchQuestionsByTextRow struct {
	QuestionText string      `json:"question_text"`
	SolutionText pgtype.Text `json:"solution_text"`
	Difficulty   pgtype.Int4 `json:"difficulty"`
}

// Search questions by text similarity
func (q *Queries) SearchQuestionsByText(ctx context.Context, arg SearchQuestionsByTextParams) ([]SearchQuestionsByTextRow, error) {
	rows, err := q.db.Query(ctx, searchQuestionsByText, arg.QuestionText, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchQuestionsByTextRow
	for rows.Next() {
		var i SearchQuestionsByTextRow
		if err := rows.Scan(&i.QuestionText, &i.SolutionText, &i.Difficulty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
