name = "vault-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[observability]
enabled = true

[[kv_namespaces]]
binding = "VAULT_STORAGE"
id = "9c25e23e6ac942218a8aac70e9e53007"

[vars]
ENV = "production"
